# Generated by Django 3.0.3 on 2020-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.CharField(max_length=10, unique=True)),
                ('led', models.CharField(max_length=3)),
                ('servo_1', models.IntegerField(default=0)),
                ('servo_2', models.IntegerField(default=0)),
                ('servo_3', models.IntegerField(default=0)),
                ('servo_4', models.IntegerField(default=0)),
            ],
        ),
    ]
