# Generated by Django 3.0.3 on 2020-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='servo_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='servo_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='servo_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='servo_4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
