# Generated by Django 3.0.4 on 2020-04-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200223_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=10, unique=True)),
                ('operation', models.CharField(max_length=3)),
            ],
        ),
    ]
