# Generated by Django 3.0.4 on 2020-04-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_operationmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmode',
            name='operation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
