# Generated by Django 3.0.4 on 2020-04-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200401_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmode',
            name='operation',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
