# Generated by Django 3.0.4 on 2020-04-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200401_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmode',
            name='status',
            field=models.CharField(default='off', max_length=3),
        ),
    ]
