# Generated by Django 3.0.4 on 2020-04-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_operationmode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20, unique=True)),
                ('img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
