# Generated by Django 3.0.4 on 2020-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_robotimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotimage',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
